---
- name : Create Jenkins
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../secret-files/ocp-oauth-secret.txt
    - ../vars/cluster-config.yaml

  collections:
    - kubernetes.core

  tasks:
    - name: Login to OCP cluster and get api_key
      k8s_auth:
        host: "{{ cluster_api_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
      register: k8s_auth_results

    - name: Ensure the target Namespace exists.
      k8s:
        state: present
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        host: "{{ cluster_api_url }}"
        validate_certs: no
        api_version: v1
        kind: Namespace
        name: "{{ template_namespace_target }}"

    - name: slurp config.xml.tpl
      slurp:
        src: "../files/config.xml.tpl"
      register: config_xml_tpl

    - name: create the configmap config.xml.tpl
      k8s:
        state: present
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        host: "{{ cluster_api_url }}"
        validate_certs: no
        namespace: "{{ template_namespace_target }}"
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: config-xml-tpl
          data:
            "config.xml.tpl": "{{ config_xml_tpl.content | b64decode }}"

    - name: Process a template in the cluster
      community.okd.openshift_process:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        host: "{{ cluster_api_url }}"
        validate_certs: no
        src: ../files/jenkins-persistent-community.yaml
        parameter_file: ../parameter-files/jenkins-parameters.env 
        namespace_target: "{{ template_namespace_target }}"
        state: rendered
      register: process_result

    - name: Create the rendered resources using apply
      community.okd.k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        host: "{{ cluster_api_url }}"
        validate_certs: no
        namespace: "{{ template_namespace_target }}"
        definition: '{{ item }}'
        wait: yes
        apply: yes
      loop: '{{ process_result.resources }}'

    - name: Get a list of all pods from used template deploy namespace
      k8s_info:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        host: "{{ cluster_api_url }}"
        kind: Pod
        namespace: "{{ template_namespace_target }}" 
        validate_certs: no
      register: pod_list

